/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdows_stas;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.Timer;

/**
 *
 * @author Stas
 */
public class OknoGlowne extends javax.swing.JFrame
{
    protected PanelWylacz panelWylacz;
    protected PanelPowiadomienie panelPowiadomienie;
    protected PanelAplikacje panelAplikacje;
    protected PanelPing panelPing;
    protected PanelConnection panelConnection;
    private SimpleDateFormat dateFormat;
    private javax.swing.Timer czas;
    private Calendar calendar;
    private TrayClass t;


    /**
     * Creates new form OknoGlowne
     */
    public OknoGlowne()
    {
        initComponents();
        panelWylacz = new PanelWylacz(OknoGlowne.this);
        panelPowiadomienie = new PanelPowiadomienie(OknoGlowne.this);
        panelAplikacje = new PanelAplikacje(OknoGlowne.this);
        panelPing = new PanelPing(OknoGlowne.this);
        panelConnection = new PanelConnection(OknoGlowne.this);
        dateFormat = new SimpleDateFormat("HH:mm:ss");
        t = new TrayClass(OknoGlowne.this);
        
        panelTabbedZakladki.add("Wylacz", panelWylacz);
        panelTabbedZakladki.add("Powiadomienie", panelPowiadomienie);
        panelTabbedZakladki.add("Aplikacje", panelAplikacje);
        panelTabbedZakladki.add("Ping", panelPing);
        panelTabbedZakladki.add("Polaczenie", panelConnection);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("zegar.png")));
       
        //javax.swing.ImageIcon iconImage = new javax.swing.ImageIcon(this.getClass().getResource("zegar.png"));
        //this.setIconImage(iconImage.getImage());

        
        czas = new javax.swing.Timer(1000, (event) -> 
                {
                    calendar = Calendar.getInstance();
                    labelGodzina.setText(dateFormat.format(calendar.getTime()));
                });
        czas.setInitialDelay(0);
        czas.start();
        
//        ukrywanie podczas minimalizowania
        addWindowStateListener((WindowEvent e) -> 
        {
            if(e.getNewState()==ICONIFIED){
                setVisible(false);
            }
        });
        
    }
    
    public void setTabConnection(boolean flaga)
    {
        if (flaga == true)
        {
            panelTabbedZakladki.setBackgroundAt(4, new Color(80, 255, 115));
            panelTabbedZakladki.setTitleAt(4, "Online");
        }
        else
        {
            panelTabbedZakladki.setBackgroundAt(4, new Color(240, 240, 240));
            panelTabbedZakladki.setTitleAt(4, "Polaczenie");
        }
    }

    public PanelWylacz getPanelWylacz()
    {
        return panelWylacz;
    }

    public PanelPowiadomienie getPanelPowiadomienie()
    {
        return panelPowiadomienie;
    }

    public PanelAplikacje getPanelAplikacje()
    {
        return panelAplikacje;
    }

    public PanelPing getPanelPing()
    {
        return panelPing;
    }

    public PanelConnection getPanelConnection()
    {
        return panelConnection;
    }
    
    public Timer getCzas()
    {
        return czas;
    }

    public JLabel getLabelGodzina()
    {
        return labelGodzina;
    }

    public JPanel getjPanel1()
    {
        return panelGodzina;
    }

    public JTabbedPane getjTabbedPane1()
    {
        return panelTabbedZakladki;
    }

    public void setjPanel1(JPanel jPanel1)
    {
        this.panelGodzina = jPanel1;
    }

    public void setjMenu1(JMenu jMenu1)
    {
        this.menuUstawienia = jMenu1;
    }

    public void setjMenu2(JMenu jMenu2)
    {
        this.menuPomoc = jMenu2;
    }

    public void setPanelWylacz(PanelWylacz panelWylacz)
    {
        this.panelWylacz = panelWylacz;
    }

    public void setPanelPowiadomienie(PanelPowiadomienie panelPowiadomienie)
    {
        this.panelPowiadomienie = panelPowiadomienie;
    }

    public void setPanelAplikacje(PanelAplikacje panelAplikacje)
    {
        this.panelAplikacje = panelAplikacje;
    }

    public void setPanelPing(PanelPing panelPing)
    {
        this.panelPing = panelPing;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelGodzina = new javax.swing.JPanel();
        labelGodzina = new javax.swing.JLabel();
        panelTabbedZakladki = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        menuUstawienia = new javax.swing.JMenu();
        menuItemPreferencje = new javax.swing.JMenuItem();
        menuPomoc = new javax.swing.JMenu();
        menuItemAnuluj = new javax.swing.JMenuItem();
        menuItemInformacje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shutdown by Stas");
        setMinimumSize(new java.awt.Dimension(628, 511));
        setResizable(false);

        panelGodzina.setBackground(new java.awt.Color(0, 153, 255));

        labelGodzina.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        labelGodzina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGodzina.setText("00:00:00");

        javax.swing.GroupLayout panelGodzinaLayout = new javax.swing.GroupLayout(panelGodzina);
        panelGodzina.setLayout(panelGodzinaLayout);
        panelGodzinaLayout.setHorizontalGroup(
            panelGodzinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGodzinaLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(labelGodzina, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGodzinaLayout.setVerticalGroup(
            panelGodzinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGodzinaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(labelGodzina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(0, 115, 255));
        menuBar.setBorder(null);

        menuUstawienia.setBackground(new java.awt.Color(0, 115, 255));
        menuUstawienia.setText("Ustawienia");

        menuItemPreferencje.setText("<html><s>Preferencje</s></html>");
        menuItemPreferencje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuItemPreferencjeActionPerformed(evt);
            }
        });
        menuUstawienia.add(menuItemPreferencje);

        menuBar.add(menuUstawienia);

        menuPomoc.setBackground(new java.awt.Color(0, 115, 255));
        menuPomoc.setText("Pomoc");

        menuItemAnuluj.setText("Anuluj wylaczanie");
        menuItemAnuluj.setToolTipText("Anuluj wylaczanie komputera w razie problemow z programem");
        menuItemAnuluj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuItemAnulujActionPerformed(evt);
            }
        });
        menuPomoc.add(menuItemAnuluj);

        menuItemInformacje.setText("Informacje");
        menuItemInformacje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuItemInformacjeActionPerformed(evt);
            }
        });
        menuPomoc.add(menuItemInformacje);

        menuBar.add(menuPomoc);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabbedZakladki, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelGodzina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelGodzina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabbedZakladki, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPreferencjeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuItemPreferencjeActionPerformed
    {//GEN-HEADEREND:event_menuItemPreferencjeActionPerformed
//        OknoUstawienia frameUstawienia = new OknoUstawienia();
//        frameUstawienia.setLocationRelativeTo(null);
//        frameUstawienia.setVisible(true);
    }//GEN-LAST:event_menuItemPreferencjeActionPerformed

    private void menuItemAnulujActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuItemAnulujActionPerformed
    {//GEN-HEADEREND:event_menuItemAnulujActionPerformed
        Funkcje funkcje = new Funkcje(this);
        funkcje.wylaczKomputer("shutdown -a", -1);
    }//GEN-LAST:event_menuItemAnulujActionPerformed

    private void menuItemInformacjeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuItemInformacjeActionPerformed
    {//GEN-HEADEREND:event_menuItemInformacjeActionPerformed
        OknoInformacje o = new OknoInformacje();
        o.setLocationRelativeTo(null);
        o.setVisible(true);
    }//GEN-LAST:event_menuItemInformacjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OknoGlowne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelGodzina;
    protected javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAnuluj;
    private javax.swing.JMenuItem menuItemInformacje;
    private javax.swing.JMenuItem menuItemPreferencje;
    private javax.swing.JMenu menuPomoc;
    private javax.swing.JMenu menuUstawienia;
    protected javax.swing.JPanel panelGodzina;
    private javax.swing.JTabbedPane panelTabbedZakladki;
    // End of variables declaration//GEN-END:variables

    public JMenuBar getjMenuBar1()
    {
        return menuBar;
    }

    
}
