/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdows_stas;

/**
 *
 * @author Stas
 */
public class OknoInformacje extends javax.swing.JFrame
{

    /**
     * Creates new form OknoPomoc
     */
    public OknoInformacje()
    {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        wyborInformacje = new javax.swing.JComboBox<>();
        labelInformacje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacje");
        setMaximumSize(new java.awt.Dimension(550, 1000));
        setMinimumSize(new java.awt.Dimension(550, 440));
        setPreferredSize(new java.awt.Dimension(550, 480));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Informacje o programie");

        wyborInformacje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ogólne", "Wyłącz", "Powiadomienie", "Aplikacje", "Ping" }));
        wyborInformacje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                wyborInformacjeActionPerformed(evt);
            }
        });

        labelInformacje.setText("<html>Werja: 0.4<br>Autor: Stanisław Szwagrzyk<br>Kontakt: stanislaw.szwagrzyk@gmail.com<br><br>Change log: <br><br>\nv0.4<br>\n-Dodana rejestracja uzytkownika i laczenie z siecia<br>\n-Zdalne wylaczenie komputera<br>\n-Minimalizacja do zasobnika<br></html>");
        labelInformacje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelInformacje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(wyborInformacje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(wyborInformacje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelInformacje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wyborInformacjeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_wyborInformacjeActionPerformed
    {//GEN-HEADEREND:event_wyborInformacjeActionPerformed
        if (wyborInformacje.getSelectedItem().toString().equals("Ogólne"))
        {
            labelInformacje.setText("<html>\nWerja: 0.3<br>\nAutor: Stanisław Szwagrzyk<br>\nKontakt: stanislaw.szwagrzyk@gmail.com<br><br>\nUpdate log: <br></html>");
        }
        else if (wyborInformacje.getSelectedItem().toString().equals("Wyłącz"))
        {
            labelInformacje.setText("<html> W kolumnie <b>Wybierz zadanie</b> po wybraniu jednej z opcji <br> <ul>   <li><b>Wyłącz komputer</b></li>   <li><b>Uruchom ponownie</b></li>   <li><b>Wyloguj</b></li>   <li><b>Szybki rozruch</b></li> </ul> "
                + "w harmonogramie zadań systemu Windows zostanie ustawione wybrane zadanie. <br><br>  W kolumnie <b>Określ czas</b> wybieramy jedno z trzech opóźnień czasowych <br> <ul>   <li><b>Od teraz za</b> - pozwala ustawić czas po jakim wykonane zostanie zadanie</li>   <li><b>O godzinie</b> - pozwala ustawić dokładną godzinę wykonania zadania</li>   <li><b>Z datą</b> - pozwala ustawić dokładną datę wykonania zadania</li> </ul>  "
                + "Abu uruchomić wybraną czynność należy kliknąć przycisk <b>Uruchom</b><br>w dolnej części okna programu.<br><Br>  Aby anulować zadanie należy kliknąć przycisk <b>Zatrzymaj</b> lub w razie jego braku<br>  z menu programu wybrać zakładkę <b>Pomoc</b> -> <b>Anuluj wyłączanie</b><br><br><br> </html>");
            
        }
        else if (wyborInformacje.getSelectedItem().toString().equals("Powiadomienie"))
        {
            labelInformacje.setText("<html>\nUruchomienie tej funkcji powiadomi użytkownika w wybrany sposób. <br>\n<ul>   <li><b>Sam dźwięk</b> - wyzwala sygnał dźwiękowy</li>   <li><b>Dźwięk</b> - wyświetla okno powiadomienia wraz z sygnałem dźwiękowym</li>   <li><b>Zapętlij</b> - Zapętla wybrane zadanie</li><li><b>Komunikat</b>"
                    + " - Pozwala wpisać komunikat wyświetlany na ekranie</li> </ul>\nNie wybranie żadnej opcji skutkuje wyświetleniem na ekranie pustego<br> okna powiadomienia.<br><br>\nW kolumnie <b>Określ czas</b> wybieramy jedno z trzech opóźnień czasowych <br> <ul>   <li><b>Od teraz za</b> - pozwala ustawić czas po jakim wykonane zostanie zadanie</li> "
                    + "  <li><b>O godzinie</b> - pozwala ustawić dokładną godzinę wykonania zadania</li>   <li><b>Z datą</b> - pozwala ustawić dokładną datę wykonania zadania</li> </ul> \n                Aby uruchomić wybraną czynność należy kliknąć przycisk <b>Uruchom</b><br>w dolnej części okna programu.<br><Br>  Aby anulować zadanie należy kliknąć przycisk <b>Zatrzymaj</b> <br><br><br> </html>\n\n\n</html>");
        
        }
        else if (wyborInformacje.getSelectedItem().toString().equals("Aplikacje"))
        {
            labelInformacje.setText("<html>\nUruchomienie tej funkcji pozwoli uzytkownikowi wykonywać operacje na aplikacjach. <br>\nRozwijana lista zawiera w sobie listę wszystkich uruchomionych na komputerze aplikacji.<br>\nWybierając jedną z nich mamy do wyboru jedną z dwóch opcji:<br>\n\n<ul>   <li><b>Wyłącz komputer</b> - wyłącza komputer gdy wybrana aplikacja zakończy dzaiłanie</li>   "
                    + "<li><b>Zamknij aplikację</b> - zamyka wybraną aplikację o określonym czasie</li></ul>\nWybranie opcji <b>Uruchom aplikację</b> pozwala nam wybrac program,<br> który zostanie otwarty po określonym czasie.<br> <br>\n\nW kolumnie <b>Określ czas</b> wybieramy jedno z trzech opóźnień czasowych <br> <ul>   <li><b>Od teraz za</b> - pozwala ustawić czas po jakim wykonane zostanie zadanie</li>   "
                    + "<li><b>O godzinie</b> - pozwala ustawić dokładną godzinę wykonania zadania</li>   <li><b>Z datą</b> - pozwala ustawić dokładną datę wykonania zadania</li> </ul> \n                Aby uruchomić wybraną czynność należy kliknąć przycisk <b>Uruchom</b><br>w dolnej części okna programu.<br><Br>  Aby anulować zadanie należy kliknąć przycisk <b>Zatrzymaj</b> <br><br><br> </html>\n\n\n</html>");
        
        }
        else if (wyborInformacje.getSelectedItem().toString().equals("Ping"))
        {
            labelInformacje.setText("<html>\nUruchomienie tej funkcji pozwoli uzytkownikowi wykonywać operacje na <br> \nsprawdzenie podstawowych parametrów łącza internetowego.<br><br>\nNa podstawie pingowania strony google.com mierzony jest ping<br>\noraz inne parametry.<br><br>\nDodatkowo ryowany jest wykres obrazujący wahania opóźnień w czasie.<br>\n\n\n</html>");
        
        }
        else
        {
            labelInformacje.setText(" ");
        }
        
    }//GEN-LAST:event_wyborInformacjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OknoInformacje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OknoInformacje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OknoInformacje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OknoInformacje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OknoInformacje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelInformacje;
    private javax.swing.JComboBox<String> wyborInformacje;
    // End of variables declaration//GEN-END:variables
}
