/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdows_stas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Stas
 */
public class PanelPing extends javax.swing.JPanel
{

    private int aktualnyPing = 0;
    private int sumaPing = 0;
    private int maxPing = 0;
    private int minPing = 9999;
    private int wyslanePakiety = 0;
    private int odebranePakiety = 0;
    private javax.swing.Timer t;
    private javax.swing.Timer t2;
    private ArrayList<Point> punkty;
    private Point p;
    private boolean isDrawing = false;
    private Graphics g;
    private javax.swing.JTabbedPane jTabbedPane1;
    private OknoGlowne oknoGlowne;
    private Funkcje funkcje;
    private javax.swing.JLabel labelSredni;
    
    
    /**
     * Creates new form PanelPing
     */
    public PanelPing(OknoGlowne oknoGlowne1)
    {
        initComponents();
        this.oknoGlowne = oknoGlowne1;
        this.jTabbedPane1 = oknoGlowne.getjTabbedPane1();
        punkty = new ArrayList<>();
        funkcje = new Funkcje(oknoGlowne);
        
        labelSredni = new javax.swing.JLabel();
        labelSredni.setBounds(173, 60, 221, 115);
        //labelSredni.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelSredni.setFont(labelPing200.getFont());
        add(labelSredni);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelWykres = new javax.swing.JPanel();
        labelPing = new javax.swing.JLabel();
        labelSredniPing = new javax.swing.JLabel();
        labelMaxPing = new javax.swing.JLabel();
        labelMinPing = new javax.swing.JLabel();
        labelWyslane = new javax.swing.JLabel();
        labelZgubione = new javax.swing.JLabel();
        labelOdebrane = new javax.swing.JLabel();
        labelSredniPingWynik = new javax.swing.JLabel();
        labelMaxPingWynik = new javax.swing.JLabel();
        labelMinPingWynik = new javax.swing.JLabel();
        labelWyslaneWynik = new javax.swing.JLabel();
        labelZgubioneWynik = new javax.swing.JLabel();
        labelOdebraneWynik = new javax.swing.JLabel();
        labelPingWynik = new javax.swing.JLabel();
        labelPing200 = new javax.swing.JLabel();
        labelPing0 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonUruchom = new javax.swing.JButton();
        buttonZatrzymaj = new javax.swing.JButton();

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Okresl czas");

        jLabel2.setText("Wybierz zadanie");

        panelWykres.setBackground(new java.awt.Color(255, 255, 255));
        panelWykres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelWykres.setPreferredSize(new java.awt.Dimension(455, 200));

        javax.swing.GroupLayout panelWykresLayout = new javax.swing.GroupLayout(panelWykres);
        panelWykres.setLayout(panelWykresLayout);
        panelWykresLayout.setHorizontalGroup(
            panelWykresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        panelWykresLayout.setVerticalGroup(
            panelWykresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        labelPing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPing.setText("Ping: ");
        labelPing.setToolTipText("Aktualny ping");

        labelSredniPing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSredniPing.setText("Sredni ping: ");

        labelMaxPing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMaxPing.setText("Max ping: ");

        labelMinPing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMinPing.setText("Min ping: ");

        labelWyslane.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWyslane.setText("Wyslane: ");
        labelWyslane.setToolTipText("Ilosc wyslanych pakietow");

        labelZgubione.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelZgubione.setText("Zgubione: ");
        labelZgubione.setToolTipText("Ilosc zgubionych pakietow");

        labelOdebrane.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOdebrane.setText("Odebrane: ");
        labelOdebrane.setToolTipText("Ilosc odebranych pakietow");

        labelSredniPingWynik.setText("0");

        labelMaxPingWynik.setText("0");

        labelMinPingWynik.setText("0");

        labelWyslaneWynik.setText("0");

        labelZgubioneWynik.setText("0");

        labelOdebraneWynik.setText("0");

        labelPingWynik.setText("0");

        labelPing200.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPing200.setText("200");

        labelPing0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPing0.setText("0");

        jPanel1.setBackground(new java.awt.Color(0, 115, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(378, 60));

        buttonUruchom.setText("Testuj");
        buttonUruchom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonUruchomActionPerformed(evt);
            }
        });

        buttonZatrzymaj.setText("Zakoncz");
        buttonZatrzymaj.setVisible(false);
        buttonZatrzymaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonZatrzymajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUruchom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonZatrzymaj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUruchom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonZatrzymaj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSredniPing)
                    .addComponent(labelPing, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMinPing, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelWyslane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelZgubione, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelOdebrane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelMaxPing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMinPingWynik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelSredniPingWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelWyslaneWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMaxPingWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelOdebraneWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelZgubioneWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPingWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPing200)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPing0)))
                .addGap(0, 0, 0)
                .addComponent(panelWykres, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPing)
                            .addComponent(labelPingWynik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSredniPing, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSredniPingWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaxPing, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMaxPingWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMinPing)
                            .addComponent(labelMinPingWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelWyslane)
                            .addComponent(labelWyslaneWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZgubione)
                            .addComponent(labelZgubioneWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelOdebrane)
                            .addComponent(labelOdebraneWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPing200)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPing0))
                            .addComponent(panelWykres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelMaxPing, labelMinPing, labelOdebrane, labelWyslane, labelZgubione});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelPing, labelSredniPing});

    }// </editor-fold>//GEN-END:initComponents

    private void buttonUruchomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonUruchomActionPerformed
    {//GEN-HEADEREND:event_buttonUruchomActionPerformed
        drawPing();
    }//GEN-LAST:event_buttonUruchomActionPerformed

    private void buttonZatrzymajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonZatrzymajActionPerformed
    {//GEN-HEADEREND:event_buttonZatrzymajActionPerformed
        panelWykres.repaint();
        t.stop();
        t2.stop();
        punkty.clear();
        isDrawing = false;
        aktualnyPing = 0;
        maxPing = 0;
        minPing = 9999;
        wyslanePakiety = 0;
        odebranePakiety = 0;
        sumaPing = 0;
        //funkcje.zmienButton(true);
        buttonZatrzymaj.setVisible(false);
        buttonUruchom.setVisible(true);
        labelSredni.setText("");
    }//GEN-LAST:event_buttonZatrzymajActionPerformed

    private void drawPing()
    {
        java.awt.BasicStroke gruba = new java.awt.BasicStroke(2);
        java.awt.BasicStroke cienka = new java.awt.BasicStroke(1);

        g = panelWykres.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        Graphics2D liniaSrednia = (Graphics2D) g;
        liniaSrednia.setColor(Color.red);
        
        t = new javax.swing.Timer(1000, (event) ->
        {
            try
            {
                aktualnyPing = funkcje.sprawdzPing();
                
                p = new Point(panelWykres.getWidth()+10, panelWykres.getHeight() - aktualnyPing);
                punkty.add(p);
                wyslanePakiety += 1;
                if (aktualnyPing>0)
                    odebranePakiety+=1;

            } catch (IOException ex)
            {
                //Logger.getLogger(OknoGlowne.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Jakis blad w drawPing()");
                panelWykres.repaint();
                t.stop();
                t2.stop();
                punkty.clear();
                isDrawing = false;
                aktualnyPing = 0;
                maxPing = 0;
                minPing = 9999;
                wyslanePakiety = 0;
                odebranePakiety = 0;
                sumaPing = 0;
                //funkcje.zmienButton(true);
                buttonZatrzymaj.setVisible(false);
                buttonUruchom.setVisible(true);
                javax.swing.JOptionPane.showMessageDialog(PanelPing.this, "Brak dostepu do internetu lub cos poszlo nei tak.");
            }
            

            panelWykres.repaint();

            if (punkty.size() > 46)
            {
                punkty.remove(0);
            }

            for(Point x : punkty)
            {
                x.setLocation(x.getX()-10, x.getY());
            }

            if (aktualnyPing > maxPing ) maxPing = aktualnyPing;
            if (aktualnyPing < minPing && aktualnyPing > 0 ) minPing = aktualnyPing;


            labelPingWynik.setText(String.valueOf(aktualnyPing));
            sumaPing += aktualnyPing;
            labelSredniPingWynik.setText(String.valueOf(sumaPing/(wyslanePakiety+1)));
            labelMinPingWynik.setText(String.valueOf(minPing));
            labelMaxPingWynik.setText(String.valueOf(maxPing));
            labelWyslaneWynik.setText(String.valueOf(wyslanePakiety));
            labelZgubioneWynik.setText(String.valueOf(wyslanePakiety - odebranePakiety));
            labelOdebraneWynik.setText(String.valueOf(odebranePakiety));
            

        });
        t.setInitialDelay(0);
        t.start();

        t2 = new javax.swing.Timer(10, (event) ->
            {
                if (jTabbedPane1.getSelectedIndex() == 3)
                {
                    int d = 0;
                    for(Point x : punkty)
                    {
                        if (d>0)
                        {
                                g2.drawLine((int) x.getX(), (int) x.getY(), (int) punkty.get(d-1).getX(), (int) punkty.get(d-1).getY());
                        }

                        g2.setColor(Color.red);
                        g2.setStroke(cienka);
                        g2.drawLine(0, panelWykres.getHeight()-(sumaPing/(wyslanePakiety+1)), panelWykres.getWidth(), panelWykres.getHeight()-(sumaPing/(wyslanePakiety+1)));
                        g2.setColor(Color.BLACK);
                        g2.setStroke(gruba);

                        if (sumaPing/(wyslanePakiety+1)<180)
                        {
                            labelSredni.setText(String.valueOf(sumaPing/(wyslanePakiety+1)));
                            labelSredni.setLocation(190, 210-(sumaPing/(wyslanePakiety+1)));
                        }
                        else
                        {
                            labelSredni.setText("");
                        }

                        d++;
                    }
                }
            });
            t2.start();
        
        //zmienButton(false);
        //funkcje.zmienButton(false);
        buttonUruchom.setVisible(false);
        buttonZatrzymaj.setVisible(true);
        
        isDrawing=true;
    }

    public boolean isIsDrawing()
    {
        return isDrawing;
    }

    public JButton getButtonUruchom()
    {
        return buttonUruchom;
    }

    public JButton getButtonZatrzymaj()
    {
        return buttonZatrzymaj;
    }

    public JPanel getjPanel1()
    {
        return jPanel1;
    }
    
   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUruchom;
    private javax.swing.JButton buttonZatrzymaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelMaxPing;
    private javax.swing.JLabel labelMaxPingWynik;
    private javax.swing.JLabel labelMinPing;
    private javax.swing.JLabel labelMinPingWynik;
    private javax.swing.JLabel labelOdebrane;
    private javax.swing.JLabel labelOdebraneWynik;
    private javax.swing.JLabel labelPing;
    private javax.swing.JLabel labelPing0;
    private javax.swing.JLabel labelPing200;
    private javax.swing.JLabel labelPingWynik;
    private javax.swing.JLabel labelSredniPing;
    private javax.swing.JLabel labelSredniPingWynik;
    private javax.swing.JLabel labelWyslane;
    private javax.swing.JLabel labelWyslaneWynik;
    private javax.swing.JLabel labelZgubione;
    private javax.swing.JLabel labelZgubioneWynik;
    private javax.swing.JPanel panelWykres;
    // End of variables declaration//GEN-END:variables
}
