/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdows_stas;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Stas
 */
public class PanelWylacz extends javax.swing.JPanel
{
    private final OknoGlowne oknoGlowne;
    private final Funkcje funkcje;
    private boolean isRunning;
    private int timeToSec;
    private Calendar calendar;
    private javax.swing.Timer odliczanie;
   

    /**
     * Creates new form PanelWylacz
     */
    public PanelWylacz(OknoGlowne oknoGlowne1)
    {
        initComponents();
        
        this.oknoGlowne = oknoGlowne1;
        funkcje = new Funkcje(oknoGlowne);
        isRunning = false;
        
        calendar = Calendar.getInstance();
        
        spinnerWylacz2.setValue(funkcje.getPrefMin());
        spinnerWylacz1.setValue(funkcje.getPrefGodz());
        spinnerWylacz4.setValue(calendar.get(Calendar.HOUR_OF_DAY));
        spinnerWylacz5.setValue(calendar.get(Calendar.MINUTE));
        
        odliczanie = new javax.swing.Timer(1000, (e) ->
                {
                });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        radioWylaczWybor = new javax.swing.ButtonGroup();
        radioWylaczGroup = new javax.swing.ButtonGroup();
        radioWylacz3 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        spinnerWylacz4 = new javax.swing.JSpinner();
        radioWylacz1 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        spinnerWylacz1 = new javax.swing.JSpinner();
        spinnerWylacz5 = new javax.swing.JSpinner();
        radioWylacz2 = new javax.swing.JRadioButton();
        spinnerWylaczData = new javax.swing.JSpinner();
        spinnerWylacz3 = new javax.swing.JSpinner();
        spinnerWylacz2 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonZatrzymaj = new javax.swing.JButton();
        buttonUruchom = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radioWylaczKomputer = new javax.swing.JRadioButton();
        radioUruchomPonownie = new javax.swing.JRadioButton();
        radioWyloguj = new javax.swing.JRadioButton();
        radioSzybkiRozruch = new javax.swing.JRadioButton();

        radioWylaczGroup.add(radioWylacz3);
        radioWylacz3.setText("Z data");
        radioWylacz3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioWylacz3ActionPerformed(evt);
            }
        });

        jLabel30.setText("Godzina");

        jLabel31.setText("Godzina");

        jLabel29.setText("Minuta");

        spinnerWylacz4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        spinnerWylacz4.setEnabled(false);

        radioWylaczGroup.add(radioWylacz1);
        radioWylacz1.setSelected(true);
        radioWylacz1.setText("Od teraz za:");
        radioWylacz1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioWylacz1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Minuta");

        spinnerWylacz1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spinnerWylacz5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        spinnerWylacz5.setEnabled(false);

        radioWylaczGroup.add(radioWylacz2);
        radioWylacz2.setText("O godzinie:");
        radioWylacz2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioWylacz2ActionPerformed(evt);
            }
        });

        spinnerWylaczData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(System.currentTimeMillis()+39536000000L), java.util.Calendar.HOUR));
        spinnerWylaczData.setEnabled(false);

        spinnerWylacz3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        spinnerWylacz2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        jLabel32.setText("Sekund");
        jLabel32.setToolTipText("");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Okresl czas");

        jLabel2.setText("Wybierz zadanie");

        jPanel1.setBackground(new java.awt.Color(0, 115, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(623, 60));

        buttonZatrzymaj.setText("Zatrzymaj");
        buttonZatrzymaj.setVisible(false);
        buttonZatrzymaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonZatrzymajActionPerformed(evt);
            }
        });

        buttonUruchom.setText("Uruchom");
        buttonUruchom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonUruchomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonZatrzymaj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUruchom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(256, 256, 256))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZatrzymaj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUruchom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        radioWylaczWybor.add(radioWylaczKomputer);
        radioWylaczKomputer.setSelected(true);
        radioWylaczKomputer.setText("Wylacz komputer");
        radioWylaczKomputer.setToolTipText("Wylacz komputer");

        radioWylaczWybor.add(radioUruchomPonownie);
        radioUruchomPonownie.setText("Uruchom ponownie");
        radioUruchomPonownie.setToolTipText("Uruchom ponownie komputer");

        radioWylaczWybor.add(radioWyloguj);
        radioWyloguj.setText("Wyloguj");
        radioWyloguj.setToolTipText("Wyloguj uzytkownika");

        radioWylaczWybor.add(radioSzybkiRozruch);
        radioSzybkiRozruch.setText("Szybki rozruch");
        radioSzybkiRozruch.setToolTipText("Wylacz komputer z opcja szybkiego uruchomienia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioWylaczKomputer)
                    .addComponent(radioUruchomPonownie)
                    .addComponent(radioWyloguj)
                    .addComponent(radioSzybkiRozruch))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(radioWylaczKomputer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioUruchomPonownie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioWyloguj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioSzybkiRozruch)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioWylacz3)
                    .addComponent(radioWylacz2)
                    .addComponent(radioWylacz1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerWylacz4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerWylacz5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addComponent(spinnerWylaczData, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerWylacz1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerWylacz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerWylacz3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))))
                .addGap(70, 70, 70))
            .addComponent(jSeparator1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spinnerWylacz1, spinnerWylacz2, spinnerWylacz3, spinnerWylacz4, spinnerWylacz5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radioWylacz1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerWylacz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(spinnerWylacz3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18))
                            .addComponent(spinnerWylacz1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(radioWylacz2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerWylacz4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(spinnerWylacz5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addComponent(radioWylacz3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerWylaczData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinnerWylacz1, spinnerWylacz2, spinnerWylacz3, spinnerWylacz4, spinnerWylacz5});

    }// </editor-fold>//GEN-END:initComponents

    private void radioWylacz3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioWylacz3ActionPerformed
    {//GEN-HEADEREND:event_radioWylacz3ActionPerformed
        spinnerWylacz1.setEnabled(false);
        spinnerWylacz2.setEnabled(false);
        spinnerWylacz3.setEnabled(false);
        spinnerWylacz4.setEnabled(false);
        spinnerWylacz5.setEnabled(false);
        spinnerWylaczData.setEnabled(true);
    }//GEN-LAST:event_radioWylacz3ActionPerformed

    private void radioWylacz1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioWylacz1ActionPerformed
    {//GEN-HEADEREND:event_radioWylacz1ActionPerformed
        spinnerWylacz1.setEnabled(true);
        spinnerWylacz2.setEnabled(true);
        spinnerWylacz3.setEnabled(true);
        spinnerWylacz4.setEnabled(false);
        spinnerWylacz5.setEnabled(false);
        spinnerWylaczData.setEnabled(false);
    }//GEN-LAST:event_radioWylacz1ActionPerformed

    private void radioWylacz2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioWylacz2ActionPerformed
    {//GEN-HEADEREND:event_radioWylacz2ActionPerformed
        spinnerWylacz1.setEnabled(false);
        spinnerWylacz2.setEnabled(false);
        spinnerWylacz3.setEnabled(false);
        spinnerWylacz4.setEnabled(true);
        spinnerWylacz5.setEnabled(true);
        spinnerWylaczData.setEnabled(false);
    }//GEN-LAST:event_radioWylacz2ActionPerformed

    private void buttonZatrzymajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonZatrzymajActionPerformed
    {//GEN-HEADEREND:event_buttonZatrzymajActionPerformed
        if (odliczanie.isRunning())
        {
            zatrzymajDzialanie();
        }
        else
        {
            oknoGlowne.getPanelAplikacje().zatrzymajDzialanie();
            oknoGlowne.getPanelPowiadomienie().zatrzymajDzialanie();
        }

    }//GEN-LAST:event_buttonZatrzymajActionPerformed

    private void buttonUruchomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonUruchomActionPerformed
    {//GEN-HEADEREND:event_buttonUruchomActionPerformed
        if (radioWylaczKomputer.isSelected())
        {
            isRunning = akcjaWylacz("shutdown -s -t ");

        }
        else if (radioUruchomPonownie.isSelected())
        {
            isRunning = akcjaWylacz("shutdown -r -c \"Zaplanowano restart komputera\" -t ");

        }
        else if (radioWyloguj.isSelected())
        {
            isRunning = akcjaWylacz("shutdown -l -c \"Zaplanowano wylogowanie uzytkownika\" -t ");

        }
        else if (radioSzybkiRozruch.isSelected())
        {
            isRunning = akcjaWylacz("shutdown -hybrid -c \"Zaplanowano wylaczenie z szybkim rozruchem\" -t ");

        }

        if (isRunning)
        {
            funkcje.zmienButton(false);
        }
        
        if ((Integer) spinnerWylacz2.getValue() != funkcje.getPrefMin() && radioWylacz1.isSelected())
        {
            funkcje.setPrefMin((Integer) spinnerWylacz2.getValue());
        }
        if ((Integer) spinnerWylacz1.getValue() != funkcje.getPrefGodz() && radioWylacz1.isSelected())
        {
            funkcje.setPrefGodz((Integer) spinnerWylacz1.getValue());
        }
        
    }//GEN-LAST:event_buttonUruchomActionPerformed

    private boolean akcjaWylacz(String dzialanie)
    {

        if (radioWylacz1.isSelected())
        {
            timeToSec = (Integer) spinnerWylacz1.getValue()*3600 + (Integer) spinnerWylacz2.getValue()*60 + (Integer) spinnerWylacz3.getValue();
            odliczanie(timeToSec);
            return funkcje.wylaczKomputer(dzialanie, timeToSec);
        }
        else if (radioWylacz2.isSelected())
        {

            calendar = Calendar.getInstance();
            calendar.set(Calendar.HOUR_OF_DAY, (Integer) spinnerWylacz4.getValue());
            calendar.set(Calendar.MINUTE, (Integer) spinnerWylacz5.getValue());
            calendar.set(Calendar.SECOND, 0);
            
            odliczanie(funkcje.obliczCzas(calendar));
            return funkcje.wylaczKomputer(dzialanie, funkcje.obliczCzas(calendar));
        }
        else if (radioWylacz3.isSelected())
        {
            calendar.setTime((Date) spinnerWylaczData.getValue());
            odliczanie(funkcje.obliczCzas(calendar));
            return funkcje.wylaczKomputer(dzialanie, funkcje.obliczCzas(calendar));
        }
        else
            return false;
    }
    
    private void odliczanie(int timeToLeft)
    {
        final int tab[] = new int[1];
        tab[0] = timeToLeft;
        oknoGlowne.getCzas().stop();
        
        odliczanie = new javax.swing.Timer(1000, (event) ->
        {
            oknoGlowne.getLabelGodzina().setText(funkcje.obliczPozostaly(tab[0]));
            if (tab[0] == 0)
            {
                odliczanie.stop();
            }
            else
            {
                tab[0]-=1;
            }
            
        });
        odliczanie.setInitialDelay(0);
        odliczanie.start();
    }
  
    public void zatrzymajDzialanie()
    {
        isRunning = !funkcje.wylaczKomputer("shutdown -a", -1);
        funkcje.zmienButton(true);
        odliczanie.stop();
        oknoGlowne.getCzas().start();
    }

    public JPanel getjPanel1()
    {
        return jPanel1;
    }

    public JButton getButtonUruchom()
    {
        return buttonUruchom;
    }

    public JButton getButtonZatrzymaj()
    {
        return buttonZatrzymaj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUruchom;
    private javax.swing.JButton buttonZatrzymaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton radioSzybkiRozruch;
    private javax.swing.JRadioButton radioUruchomPonownie;
    private javax.swing.JRadioButton radioWylacz1;
    private javax.swing.JRadioButton radioWylacz2;
    private javax.swing.JRadioButton radioWylacz3;
    private javax.swing.ButtonGroup radioWylaczGroup;
    private javax.swing.JRadioButton radioWylaczKomputer;
    private javax.swing.ButtonGroup radioWylaczWybor;
    private javax.swing.JRadioButton radioWyloguj;
    private javax.swing.JSpinner spinnerWylacz1;
    private javax.swing.JSpinner spinnerWylacz2;
    private javax.swing.JSpinner spinnerWylacz3;
    private javax.swing.JSpinner spinnerWylacz4;
    private javax.swing.JSpinner spinnerWylacz5;
    private javax.swing.JSpinner spinnerWylaczData;
    // End of variables declaration//GEN-END:variables
}
