/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdows_stas;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Stas
 */
public class PanelAplikacje extends javax.swing.JPanel
{
    private final OknoGlowne oknoGlowne;
    private final Funkcje funkcje;
    private String wybranyProgramUruchom;
    private FileFilter ft;
    private String wybranyProgram;
    private javax.swing.Timer sprProgram;
    private javax.swing.Timer odliczanie;
    private ArrayList<String> procesySprawdz;
    private ArrayList<String> procesy;
    private boolean isClosed=false;
    private int timeToSec;
    private Calendar calendar;
    private int sprawdzOpoznienie;

    /**
     * Creates new form PanelAplikacje
     */
    public PanelAplikacje(OknoGlowne oknoGlowne1)
    {
        UIManager.put("FileChooser.cancelButtonText", "Zamknij");
        UIManager.put("FileChooser.cancelButtonToolTipText", "Porzuca dotychczas wybrany element");
        UIManager.put("FileChooser.openButtonText", "Otwórz");
        UIManager.put("FileChooser.openButtonToolTipText", "Otworz wybrany plik");
        UIManager.put("FileChooser.acceptAllFileFilterText", "Wszystkie pliki");
        UIManager.put("FileChooser.fileNameLabelText", "Nazwa pliku");
        UIManager.put("FileChooser.filesOfTypeLabelText", "Typ pliku");
        UIManager.put("FileChooser.lookInLabelText", "Źródło");
        UIManager.put("FileChooser.directoryOpenButtonText", "Otwórz");
        UIManager.put("FileChooser.directoryOpenButtonToolTipText", "Otwórz plik");
        UIManager.put("FileChooser.upFolderToolTipText", "Poprzedni folder");
        UIManager.put("FileChooser.newFolderToolTipText", "Utwórz nowy folder");
        UIManager.put("FileChooser.listViewButtonToolTipText", "Lista");
        UIManager.put("FileChooser.detailsViewButtonToolTipText", "Detale");
        UIManager.put("FileChooser.homeFolderToolTipText", "Pulpit");
        UIManager.put("FileChooser.homeFolderAccessibleName", "Pulpit");
        UIManager.put("FileChooser.openDialogTitleText", "Otwórz");
        
        initComponents();
        
        oknoGlowne = oknoGlowne1;
        funkcje = new Funkcje(oknoGlowne);
        ft = new FileNameExtensionFilter("Aplikacje", "exe");
        procesy = funkcje.pokazProcesy();
        
        calendar = Calendar.getInstance();
        spinnerAplikacje2.setValue(funkcje.getPrefMin());
        spinnerAplikacje1.setValue(funkcje.getPrefGodz());
        spinnerAplikacje4.setValue(calendar.get(Calendar.HOUR_OF_DAY));
        spinnerAplikacje5.setValue(calendar.get(Calendar.MINUTE));
        
        sprProgram = new javax.swing.Timer(1000, (e) -> 
                {
                });
        odliczanie = new javax.swing.Timer(1000, (e) ->
                {
                });
        
        for (String x : procesy)
        {
            listProcesy.addItem(x);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        radioAplikacjeWybor = new javax.swing.ButtonGroup();
        radioAplikacjeGroup = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        radioAplikacje6 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        spinnerAplikacje4 = new javax.swing.JSpinner();
        radioAplikacje4 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        spinnerAplikacje1 = new javax.swing.JSpinner();
        spinnerAplikacje5 = new javax.swing.JSpinner();
        radioAplikacje5 = new javax.swing.JRadioButton();
        spinnerAplikacjeData = new javax.swing.JSpinner();
        spinnerAplikacje3 = new javax.swing.JSpinner();
        spinnerAplikacje2 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioAplikacje1 = new javax.swing.JRadioButton();
        radioAplikacje2 = new javax.swing.JRadioButton();
        radioAplikacje3 = new javax.swing.JRadioButton();
        buttonWybierzProgram = new javax.swing.JButton();
        listProcesy = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        buttonUruchom = new javax.swing.JButton();
        buttonZatrzymaj = new javax.swing.JButton();

        radioAplikacjeGroup.add(radioAplikacje6);
        radioAplikacje6.setText("Z data");
        radioAplikacje6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAplikacje6ActionPerformed(evt);
            }
        });

        jLabel30.setText("Godzina");

        jLabel31.setText("Godzina");

        jLabel29.setText("Minuta");

        spinnerAplikacje4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        spinnerAplikacje4.setEnabled(false);

        radioAplikacjeGroup.add(radioAplikacje4);
        radioAplikacje4.setSelected(true);
        radioAplikacje4.setText("Od teraz za:");
        radioAplikacje4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAplikacje4ActionPerformed(evt);
            }
        });

        jLabel28.setText("Minuta");

        spinnerAplikacje1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spinnerAplikacje5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        spinnerAplikacje5.setEnabled(false);

        radioAplikacjeGroup.add(radioAplikacje5);
        radioAplikacje5.setText("O godzinie:");
        radioAplikacje5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAplikacje5ActionPerformed(evt);
            }
        });

        spinnerAplikacjeData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(1903852260000L), java.util.Calendar.HOUR));
        spinnerAplikacjeData.setEnabled(false);

        spinnerAplikacje3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        spinnerAplikacje2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        jLabel32.setText("Sekund");
        jLabel32.setToolTipText("");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Okresl czas");

        jLabel2.setText("Wybierz zadanie");

        radioAplikacjeWybor.add(radioAplikacje1);
        radioAplikacje1.setSelected(true);
        radioAplikacje1.setText("Wylacz komputer");
        radioAplikacje1.setToolTipText("Wylacza komputer po zakonczeniu aplikacji");
        radioAplikacje1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAplikacje1ActionPerformed(evt);
            }
        });

        radioAplikacjeWybor.add(radioAplikacje2);
        radioAplikacje2.setText("Zamknij aplikacje");
        radioAplikacje2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAplikacje2ActionPerformed(evt);
            }
        });

        radioAplikacjeWybor.add(radioAplikacje3);
        radioAplikacje3.setText("Uruchom aplikacje");
        radioAplikacje3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAplikacje3ActionPerformed(evt);
            }
        });

        buttonWybierzProgram.setText("Wybierz program");
        buttonWybierzProgram.setToolTipText("Musisz wybrac aplikacje typu .exe");
        buttonWybierzProgram.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonWybierzProgramActionPerformed(evt);
            }
        });
        buttonWybierzProgram.setVisible(false);

        listProcesy.setPreferredSize(new java.awt.Dimension(133, 24));
        listProcesy.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                listProcesyMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 115, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 60));

        buttonUruchom.setText("Uruchom");
        buttonUruchom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonUruchomActionPerformed(evt);
            }
        });

        buttonZatrzymaj.setText("Zatrzymaj");
        buttonZatrzymaj.setVisible(false);
        buttonZatrzymaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonZatrzymajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUruchom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonZatrzymaj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUruchom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonZatrzymaj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonWybierzProgram)
                    .addComponent(radioAplikacje2)
                    .addComponent(radioAplikacje1)
                    .addComponent(listProcesy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAplikacje3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAplikacje6)
                    .addComponent(radioAplikacje5)
                    .addComponent(radioAplikacje4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerAplikacjeData, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerAplikacje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAplikacje5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerAplikacje1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAplikacje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAplikacje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))))
                .addGap(80, 80, 80))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spinnerAplikacje1, spinnerAplikacje2, spinnerAplikacje3, spinnerAplikacje4, spinnerAplikacje5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radioAplikacje4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerAplikacje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(spinnerAplikacje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18))
                            .addComponent(spinnerAplikacje1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(radioAplikacje5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerAplikacje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(spinnerAplikacje5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addComponent(radioAplikacje6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerAplikacjeData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(listProcesy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioAplikacje1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioAplikacje2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioAplikacje3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonWybierzProgram)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinnerAplikacje1, spinnerAplikacje2, spinnerAplikacje3, spinnerAplikacje4, spinnerAplikacje5});

    }// </editor-fold>//GEN-END:initComponents

    private void radioAplikacje6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioAplikacje6ActionPerformed
    {//GEN-HEADEREND:event_radioAplikacje6ActionPerformed
        spinnerAplikacje1.setEnabled(false);
        spinnerAplikacje2.setEnabled(false);
        spinnerAplikacje3.setEnabled(false);
        spinnerAplikacje4.setEnabled(false);
        spinnerAplikacje5.setEnabled(false);
        spinnerAplikacjeData.setEnabled(true);
    }//GEN-LAST:event_radioAplikacje6ActionPerformed

    private void radioAplikacje4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioAplikacje4ActionPerformed
    {//GEN-HEADEREND:event_radioAplikacje4ActionPerformed
        spinnerAplikacje1.setEnabled(true);
        spinnerAplikacje2.setEnabled(true);
        spinnerAplikacje3.setEnabled(true);
        spinnerAplikacje4.setEnabled(false);
        spinnerAplikacje5.setEnabled(false);
        spinnerAplikacjeData.setEnabled(false);
    }//GEN-LAST:event_radioAplikacje4ActionPerformed

    private void radioAplikacje5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioAplikacje5ActionPerformed
    {//GEN-HEADEREND:event_radioAplikacje5ActionPerformed
        spinnerAplikacje1.setEnabled(false);
        spinnerAplikacje2.setEnabled(false);
        spinnerAplikacje3.setEnabled(false);
        spinnerAplikacje4.setEnabled(true);
        spinnerAplikacje5.setEnabled(true);
        spinnerAplikacjeData.setEnabled(false);
    }//GEN-LAST:event_radioAplikacje5ActionPerformed

    private void radioAplikacje1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioAplikacje1ActionPerformed
    {//GEN-HEADEREND:event_radioAplikacje1ActionPerformed
        if(buttonWybierzProgram.isVisible())
        {
            buttonWybierzProgram.setVisible(false);
        }

        if (radioAplikacje4.isEnabled())
        {
            radioAplikacje4.setEnabled(false);
            radioAplikacje5.setEnabled(false);
            radioAplikacje6.setEnabled(false);
            spinnerAplikacje1.setEnabled(false);
            spinnerAplikacje2.setEnabled(false);
            spinnerAplikacje3.setEnabled(false);
            spinnerAplikacje4.setEnabled(false);
            spinnerAplikacje5.setEnabled(false);
            spinnerAplikacjeData.setEnabled(false);
        }
    }//GEN-LAST:event_radioAplikacje1ActionPerformed

    private void radioAplikacje2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioAplikacje2ActionPerformed
    {//GEN-HEADEREND:event_radioAplikacje2ActionPerformed
        if(buttonWybierzProgram.isVisible())
        {
            buttonWybierzProgram.setVisible(false);
        }

        if (!radioAplikacje4.isEnabled() && radioAplikacje4.isSelected())
        {
            radioAplikacje4.setEnabled(true);
            radioAplikacje5.setEnabled(true);
            radioAplikacje6.setEnabled(true);
            spinnerAplikacje1.setEnabled(true);
            spinnerAplikacje2.setEnabled(true);
            spinnerAplikacje3.setEnabled(true);
            spinnerAplikacje4.setEnabled(false);
            spinnerAplikacje5.setEnabled(false);
            spinnerAplikacjeData.setEnabled(false);
        }
        else if (!radioAplikacje5.isEnabled() && radioAplikacje5.isSelected())
        {
            radioAplikacje4.setEnabled(true);
            radioAplikacje5.setEnabled(true);
            radioAplikacje6.setEnabled(true);
            spinnerAplikacje1.setEnabled(false);
            spinnerAplikacje2.setEnabled(false);
            spinnerAplikacje3.setEnabled(false);
            spinnerAplikacje4.setEnabled(true);
            spinnerAplikacje5.setEnabled(true);
            spinnerAplikacjeData.setEnabled(false);
        }
        else if (!radioAplikacje6.isEnabled() && radioAplikacje6.isSelected())
        {
            radioAplikacje4.setEnabled(true);
            radioAplikacje5.setEnabled(true);
            radioAplikacje6.setEnabled(true);
            spinnerAplikacje1.setEnabled(false);
            spinnerAplikacje2.setEnabled(false);
            spinnerAplikacje3.setEnabled(false);
            spinnerAplikacje4.setEnabled(false);
            spinnerAplikacje5.setEnabled(false);
            spinnerAplikacjeData.setEnabled(true);
        }

    }//GEN-LAST:event_radioAplikacje2ActionPerformed

    private void radioAplikacje3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioAplikacje3ActionPerformed
    {//GEN-HEADEREND:event_radioAplikacje3ActionPerformed
        buttonWybierzProgram.setVisible(true);

        if (!radioAplikacje4.isEnabled() && radioAplikacje4.isSelected())
        {
            radioAplikacje4.setEnabled(true);
            radioAplikacje5.setEnabled(true);
            radioAplikacje6.setEnabled(true);
            spinnerAplikacje1.setEnabled(true);
            spinnerAplikacje2.setEnabled(true);
            spinnerAplikacje3.setEnabled(true);
            spinnerAplikacje4.setEnabled(false);
            spinnerAplikacje5.setEnabled(false);
            spinnerAplikacjeData.setEnabled(false);
        }
        else if (!radioAplikacje5.isEnabled() && radioAplikacje5.isSelected())
        {
            radioAplikacje4.setEnabled(true);
            radioAplikacje5.setEnabled(true);
            radioAplikacje6.setEnabled(true);
            spinnerAplikacje1.setEnabled(false);
            spinnerAplikacje2.setEnabled(false);
            spinnerAplikacje3.setEnabled(false);
            spinnerAplikacje4.setEnabled(true);
            spinnerAplikacje5.setEnabled(true);
            spinnerAplikacjeData.setEnabled(false);
        }
        else if (!radioAplikacje6.isEnabled() && radioAplikacje6.isSelected())
        {
            radioAplikacje4.setEnabled(true);
            radioAplikacje5.setEnabled(true);
            radioAplikacje6.setEnabled(true);
            spinnerAplikacje1.setEnabled(false);
            spinnerAplikacje2.setEnabled(false);
            spinnerAplikacje3.setEnabled(false);
            spinnerAplikacje4.setEnabled(false);
            spinnerAplikacje5.setEnabled(false);
            spinnerAplikacjeData.setEnabled(true);
        }

    }//GEN-LAST:event_radioAplikacje3ActionPerformed

    private void buttonWybierzProgramActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonWybierzProgramActionPerformed
    {//GEN-HEADEREND:event_buttonWybierzProgramActionPerformed
        fileChooser.addChoosableFileFilter(ft);
        int wysOkno = fileChooser.showOpenDialog(this);
        if(wysOkno == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            java.io.File plik = fileChooser.getSelectedFile();
            String nazwaPliku = plik.toString( );
            if (nazwaPliku.endsWith(".exe"))
            {
                wybranyProgramUruchom = nazwaPliku.replace("\\", "\\\\");
                    //javax.swing.JOptionPane.showMessageDialog(OknoGlowne.this, nazwaPliku);
                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Wybrany plik nie jest aplikacja .exe");
                    nazwaPliku = "";
                }

            }
    }//GEN-LAST:event_buttonWybierzProgramActionPerformed

    private void buttonUruchomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonUruchomActionPerformed
    {//GEN-HEADEREND:event_buttonUruchomActionPerformed
        if (radioAplikacje1.isSelected())
            {
                wybranyProgram = listProcesy.getSelectedItem().toString();
                
                sprProgram = new javax.swing.Timer(5000, (event) ->
                {
                    procesySprawdz = funkcje.pokazProcesy();

                    for (String x : procesySprawdz)
                    {
                        if (x.equals(wybranyProgram) == true)
                        {
                            isClosed = false;
                            break;
                        }
                    }
                    
                    if (isClosed)
                    {
                        sprProgram.stop();
                        funkcje.wylaczKomputer("shutdown -s -t ", 3);
                        //System.out.println("Zamykam");
                    }
                    isClosed = true;
                });
                
                sprProgram.start();
                //isRunning = true;
                funkcje.zmienButton(false);
                
            }
            else if (radioAplikacje2.isSelected())
            {
                if (radioAplikacje4.isSelected())
                {
                    wybranyProgram = listProcesy.getSelectedItem().toString();
                    timeToSec = (Integer) spinnerAplikacje1.getValue()*3600 + (Integer) spinnerAplikacje2.getValue()*60 + (Integer) spinnerAplikacje3.getValue();
                    
                    sprProgram = new javax.swing.Timer(timeToSec*1000, (event) ->
                    {
                        funkcje.wylaczKomputer("taskkill /f /im " + wybranyProgram, -1);
                        //isRunning = false;
                        funkcje.zmienButton(true);
                        oknoGlowne.getCzas().start();
                        
                        
                    });
                    
                    try{
                        odliczanie(timeToSec);
                        sprProgram.setRepeats(false);
                        sprProgram.start();
                        //isRunning = true;
                        funkcje.zmienButton(false);
                    }catch(Exception ex){
                        javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Cos poszlo nie tak!\n" + ex);
                        sprProgram.stop();
                        //isRunning = false;
                        funkcje.zmienButton(true);
                        oknoGlowne.getCzas().start();
                    }
                    
                }
                else if (radioAplikacje5.isSelected())
                {
                    wybranyProgram = listProcesy.getSelectedItem().toString();

                    calendar = Calendar.getInstance();
                    calendar.set(Calendar.HOUR_OF_DAY, (Integer) spinnerAplikacje4.getValue());
                    calendar.set(Calendar.MINUTE, (Integer) spinnerAplikacje5.getValue());
                    calendar.set(Calendar.SECOND, 0);
                    
                    sprawdzOpoznienie = funkcje.obliczCzas(calendar);
                    if (sprawdzOpoznienie > -1)
                    {
                        sprProgram = new javax.swing.Timer(sprawdzOpoznienie*1000, (event) ->
                        {
                            funkcje.wylaczKomputer("taskkill /f /im " + wybranyProgram, -1);
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();

                        });

                        try{
                            odliczanie(sprawdzOpoznienie);
                            sprProgram.setRepeats(false);
                            sprProgram.start();
                            //isRunning = true;
                            funkcje.zmienButton(false);
                        }catch(Exception ex){
                            javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Cos poszlo nie tak!\n" + ex);
                            sprProgram.stop();
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();
                        }
                    }
                }
                else if (radioAplikacje6.isSelected())
                {
                    wybranyProgram = listProcesy.getSelectedItem().toString();
                    calendar.setTime((Date) spinnerAplikacjeData.getValue());
                    
                    sprawdzOpoznienie = funkcje.obliczCzas(calendar);
                    if (sprawdzOpoznienie > -1)
                    {
                        sprProgram = new javax.swing.Timer(sprawdzOpoznienie*1000, (event) ->
                        {
                            funkcje.wylaczKomputer("taskkill /f /im " + wybranyProgram, -1);
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();

                        });

                        try{
                            odliczanie(sprawdzOpoznienie);
                            sprProgram.setRepeats(false);
                            sprProgram.start();
                            //isRunning = true;
                            funkcje.zmienButton(false);
                        }catch(Exception ex){
                            javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Cos poszlo nie tak!\n" + ex);
                            sprProgram.stop();
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();
                        }
                    }
                }
            }
            
            else if (radioAplikacje3.isSelected())
            {    
                if (radioAplikacje4.isSelected())
                {
                    if (wybranyProgramUruchom.equals(""))
                    {
                        javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Najpierw wybierz program.");
                    }
                    else
                    {

                        timeToSec = (Integer) spinnerAplikacje1.getValue()*3600 + (Integer) spinnerAplikacje2.getValue()*60 + (Integer) spinnerAplikacje3.getValue();

                        sprProgram = new javax.swing.Timer(timeToSec*1000, (event) ->
                        {
                            funkcje.uruchomProgram(wybranyProgramUruchom);
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();


                        });

                        try{
                            odliczanie(timeToSec);
                            sprProgram.setRepeats(false);
                            sprProgram.start();
                            //isRunning = true;
                            funkcje.zmienButton(false);
                        }catch(Exception ex){
                            javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Cos poszlo nie tak!\n" + ex);
                            sprProgram.stop();
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();
                        }
                    }

                }
                else if (radioAplikacje5.isSelected())
                {
                    wybranyProgram = listProcesy.getSelectedItem().toString();

                    calendar = Calendar.getInstance();
                    calendar.set(Calendar.HOUR_OF_DAY, (Integer) spinnerAplikacje4.getValue());
                    calendar.set(Calendar.MINUTE, (Integer) spinnerAplikacje5.getValue());
                    calendar.set(Calendar.SECOND, 0);

                    sprawdzOpoznienie = funkcje.obliczCzas(calendar);
                    if (sprawdzOpoznienie > -1)
                    {
                        sprProgram = new javax.swing.Timer(sprawdzOpoznienie*1000, (event) ->
                        {
                            funkcje.uruchomProgram(wybranyProgramUruchom);
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();

                        });

                        try{
                            odliczanie(sprawdzOpoznienie);
                            sprProgram.setRepeats(false);
                            sprProgram.start();
                            //isRunning = true;
                            funkcje.zmienButton(false);
                        }catch(Exception ex){
                            javax.swing.JOptionPane.showMessageDialog(oknoGlowne, "Cos poszlo nie tak!\n" + ex);
                            sprProgram.stop();
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();
                        }
                    }

                }
                else if (radioAplikacje6.isSelected())
                {
                    wybranyProgram = listProcesy.getSelectedItem().toString();
                    calendar.setTime((Date) spinnerAplikacjeData.getValue());
                    
                    sprawdzOpoznienie = funkcje.obliczCzas(calendar);
                    if (sprawdzOpoznienie > -1)
                    {
                        sprProgram = new javax.swing.Timer(sprawdzOpoznienie*1000, (event) ->
                        {
                            funkcje.uruchomProgram(wybranyProgramUruchom);
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();

                        });

                        try{
                            odliczanie(sprawdzOpoznienie);
                            sprProgram.setRepeats(false);
                            sprProgram.start();
                            //isRunning = true;
                            funkcje.zmienButton(false);
                        }catch(Exception ex){
                            //javax.swing.JOptionPane.showMessageDialog(OknoGlowne.this, "Cos poszlo nie tak!\n" + ex);
                            sprProgram.stop();
                            //isRunning = false;
                            funkcje.zmienButton(true);
                            oknoGlowne.getCzas().start();
                        }
                    }
                }
            }
        
        if ((Integer) spinnerAplikacje2.getValue() != funkcje.getPrefMin() && radioAplikacje4.isSelected())
        {
            funkcje.setPrefMin((Integer) spinnerAplikacje2.getValue());
        }
        if ((Integer) spinnerAplikacje1.getValue() != funkcje.getPrefGodz() && radioAplikacje4.isSelected())
        {
            funkcje.setPrefGodz((Integer) spinnerAplikacje1.getValue());
        }
        
    }//GEN-LAST:event_buttonUruchomActionPerformed

    
    private void buttonZatrzymajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonZatrzymajActionPerformed
    {//GEN-HEADEREND:event_buttonZatrzymajActionPerformed
        if (sprProgram.isRunning())
        {
            zatrzymajDzialanie();
            
        }
        else
        {
            
            oknoGlowne.getPanelPowiadomienie().zatrzymajDzialanie();
            oknoGlowne.getPanelWylacz().zatrzymajDzialanie();
        }
    }//GEN-LAST:event_buttonZatrzymajActionPerformed

    private void listProcesyMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_listProcesyMouseClicked
    {//GEN-HEADEREND:event_listProcesyMouseClicked
        procesy = funkcje.pokazProcesy();
        listProcesy.removeAllItems();
        
        for (String x : procesy)
        {
            listProcesy.addItem(x);
        }
    }//GEN-LAST:event_listProcesyMouseClicked

    private void odliczanie(int timeToLeft)
    {
        final int tab[] = new int[1];
        tab[0] = timeToLeft;
        oknoGlowne.getCzas().stop();
        
        odliczanie = new javax.swing.Timer(1000, (event) ->
        {
            oknoGlowne.getLabelGodzina().setText(funkcje.obliczPozostaly(tab[0]));
            if (tab[0] == 0)
            {
                odliczanie.stop();
            }
            else
            {
                tab[0]-=1;
            }
            
        });
        odliczanie.setInitialDelay(0);
        odliczanie.start();
    }
    
    public void zatrzymajDzialanie()
    {
        sprProgram.stop();
        funkcje.zmienButton(true);
        odliczanie.stop();
        oknoGlowne.getCzas().start();
    }
    
        public JPanel getjPanel1()
    {
        return jPanel1;
    }

    public JButton getButtonUruchom()
    {
        return buttonUruchom;
    }

    public JButton getButtonZatrzymaj()
    {
        return buttonZatrzymaj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUruchom;
    private javax.swing.JButton buttonWybierzProgram;
    private javax.swing.JButton buttonZatrzymaj;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> listProcesy;
    private javax.swing.JRadioButton radioAplikacje1;
    private javax.swing.JRadioButton radioAplikacje2;
    private javax.swing.JRadioButton radioAplikacje3;
    private javax.swing.JRadioButton radioAplikacje4;
    private javax.swing.JRadioButton radioAplikacje5;
    private javax.swing.JRadioButton radioAplikacje6;
    private javax.swing.ButtonGroup radioAplikacjeGroup;
    private javax.swing.ButtonGroup radioAplikacjeWybor;
    private javax.swing.JSpinner spinnerAplikacje1;
    private javax.swing.JSpinner spinnerAplikacje2;
    private javax.swing.JSpinner spinnerAplikacje3;
    private javax.swing.JSpinner spinnerAplikacje4;
    private javax.swing.JSpinner spinnerAplikacje5;
    private javax.swing.JSpinner spinnerAplikacjeData;
    // End of variables declaration//GEN-END:variables
}
